# Generated by Django 2.2.9 on 2020-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='unit',
            field=models.CharField(default='Rs', max_length=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unit',
            field=models.CharField(default='kgs', max_length=5),
        ),
    ]
