# Generated by Django 2.2.9 on 2020-02-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_auto_20200226_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='customer',
            new_name='transporter',
        ),
    ]
